import { EventType, EventStatus } from './enums';
import { Participant } from './participant.model';
import { Schedule } from './schedule.model';
import { FileUpload } from './file.model';

export interface Event {
    id?: string;
    createdAt?: string;
    updatedAt?: string;
    title: string;
    description?: string;
    startDate: string;
    endDate: string;
    globalStartTime?: string;
    globalEndTime?: string;
    meetingLink?: string;
    pays?: string;
    ville?: string;
    status: EventStatus;
    type: EventType;
    lieuType?: string;
    salle?: string;
    nomLieu?: string;
    schedules?: Schedule[];
    files?: FileUpload[];
    participants?: Participant[];
    structures?: string[];
    changeSuggestions?: string;
    rejectionReason?: string;
    validationComment?: string;
    creatorEmail?: string;
    creatorUsername?: string;
    creatorRole?: string;
    delegueNom?: string;
    delegueEmail?: string;
    delegueMotif?: string;
    estDelegue?: boolean;
    delegueDate?: string;
    delegueParEmail?: string;
}